version: 2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.66.0
    steps:
      - checkout
      - run:
          name: Clippy
          command: "cargo clippy -- -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used -W clippy::expect_used -D warnings"
      - run:
          name: Run Tests
          command: "cargo test"

